#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"HondaBrakePIDParams", {PERSISTENT, FLOAT}},
    {"HondaCarGasScaleParams", {PERSISTENT, FLOAT}},
    {"HondaCreepFactorParams", {PERSISTENT, FLOAT}},
    {"HondaFeedForwardParams", {PERSISTENT, FLOAT}},
    {"HondaGasAlpha00Params", {PERSISTENT, FLOAT}},
    {"HondaGasAlpha10Params", {PERSISTENT, FLOAT}},
    {"HondaGasAlpha20Params", {PERSISTENT, FLOAT}},
    {"HondaGasAlpha30Params", {PERSISTENT, FLOAT}},
    {"HondaGasAlphaLowParams", {PERSISTENT, FLOAT}},
    {"HondaGasAlphaParams", {PERSISTENT, FLOAT}},
    {"HondaGasFactor00Params", {PERSISTENT, FLOAT}},
    {"HondaGasFactor10Params", {PERSISTENT, FLOAT}},
    {"HondaGasFactor20Params", {PERSISTENT, FLOAT}},
    {"HondaGasFactor30Params", {PERSISTENT, FLOAT}},
    {"HondaGasFactorLowParams", {PERSISTENT, FLOAT}},
    {"HondaGasFactorParams", {PERSISTENT, FLOAT}},
    {"HondaLaunchDvParams", {PERSISTENT, FLOAT}},
    {"HondaLaunchDvBreakParams", {PERSISTENT, FLOAT}},
    {"HondaLaunchGasParams", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlpha05Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlpha15Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlpha25Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlpha35Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlphaLowParams", {PERSISTENT, FLOAT}},
    {"HondaSpeedAlphaParams", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactor05Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactor15Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactor25Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactor35Params", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactorLowParams", {PERSISTENT, FLOAT}},
    {"HondaSpeedFactorParams", {PERSISTENT, FLOAT}},
    {"HondaWindFactorParams", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor05Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor10Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor15Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor20Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor25Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor30Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor35Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor40Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor45Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor50Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor55Params", {PERSISTENT, FLOAT}},
    {"HondaLatAccelFactor60Params", {PERSISTENT, FLOAT}},
    {"HondaSatAccelParams", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorN010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaN010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatFactorP100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerLatAlphaP100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha010Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha020Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha030Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha040Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha050Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha060Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha070Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha080Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha090Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueFactor100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerTorqueAlpha100Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor00Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha00Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor10Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha10Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor20Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha20Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor40Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha40Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor50Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha50Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor60Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha60Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedFactor70Params", {PERSISTENT, FLOAT}},
    {"HondaSteerSpeedAlpha70Params", {PERSISTENT, FLOAT}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LaneCentering", {PERSISTENT, BOOL, "0"}},
    {"LaneCenteringE2EAuthority", {PERSISTENT, FLOAT, "1.0"}},
    {"LaneCenteringPauseOnSignal", {PERSISTENT, BOOL, "1"}},
    {"LaneCenterOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UsbGpuPresent", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuCompiled", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"Version", {PERSISTENT, STRING}},
};
